name: Build Docker image and publish it with latest tag

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag khassanov/greeter:latest

      - name: Login to Docker Hub registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u khassanov --password-stdin

      - name: Publish the image
        run: docker push khassanov/greeter:latest

      - name: Update image on 1.contabo.khassanov.xyz
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: echo "Hello, $(whoami)!"
